BEGIN;

ALTER TABLE public.lawyer_analytics
  ADD COLUMN IF NOT EXISTS chart_top_party_1_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_1_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_1_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_2_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_2_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_2_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_3_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_3_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_3_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_4_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_4_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_4_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_5_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_5_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_5_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_1_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_1_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_1_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_2_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_2_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_2_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_3_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_3_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_3_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_4_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_4_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_4_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_5_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_5_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_party_5_settlement_rate numeric(6,2) DEFAULT 0,

  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_1_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_1_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_1_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_2_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_2_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_2_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_3_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_3_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_3_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_4_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_4_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_4_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_5_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_5_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_5_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_1_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_1_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_1_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_2_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_2_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_2_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_3_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_3_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_3_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_4_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_4_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_4_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_5_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_5_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_opp_lawyer_5_settlement_rate numeric(6,2) DEFAULT 0,

  ADD COLUMN IF NOT EXISTS chart_top_judge_1_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_1_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_1_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_2_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_2_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_2_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_3_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_3_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_3_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_4_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_4_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_4_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_5_won integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_5_lost integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_5_settled integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_1_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_1_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_1_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_2_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_2_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_2_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_3_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_3_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_3_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_4_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_4_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_4_settlement_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_5_win_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_5_loss_rate numeric(6,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS chart_top_judge_5_settlement_rate numeric(6,2) DEFAULT 0;

COMMENT ON COLUMN public.lawyer_analytics.chart_top_party_1_won IS 'Top opponent party #1: count of wins for this lawyer in those cases.';
COMMENT ON COLUMN public.lawyer_analytics.chart_top_party_1_lost IS 'Top opponent party #1: count of losses for this lawyer in those cases.';
COMMENT ON COLUMN public.lawyer_analytics.chart_top_party_1_settled IS 'Top opponent party #1: count of settled cases for this lawyer in those cases.';
COMMENT ON COLUMN public.lawyer_analytics.chart_top_party_1_win_rate IS 'Top opponent party #1: win rate in percentage.';
COMMENT ON COLUMN public.lawyer_analytics.chart_top_party_1_loss_rate IS 'Top opponent party #1: loss rate in percentage.';
COMMENT ON COLUMN public.lawyer_analytics.chart_top_party_1_settlement_rate IS 'Top opponent party #1: settlement rate in percentage.';

COMMIT;
